name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
           login-server: casestudyunext.azurecr.io
           username: CaseStudyUnext
           password: xKeLXBoMNDtAG/OoJBwkDgWRq4r7RMN5WOJaIbPTkE+ACRBykGzd
      - run: |
          docker build . -t casestudyunext.azurecr.io/sparsh:${{ github.sha }}
          docker push casestudyunext.azurecr.io/sparsh:${{ github.sha }}

